version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: PodServer
    environment:
      - AUDIOBOOKSHELF_UID=1000
      - AUDIOBOOKSHELF_GID=1000
      - PUID=1000
      - PGID=1000
    ports:
      - "13380:80"
    volumes:
      - "/mnt/AudioBooks:/audiobooks"
      - "/mnt/Podcasts:/podcasts"
      - "/home/omar/DockerConfs/PodServer/config:/config"
      - "/home/omar/DockerConfs/PodServer/metadata:/metadata"
