---
version: "2.1"
services:
  booksonic-air:
    image: linuxserver/booksonic-air:latest
    container_name: booksonic-air
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      # - CONTEXT_PATH=url-base #optional
    volumes:
      - ${Master_Path}/Booksonic/config:/config
      - ${Master_Path}/Booksonic/audiobooks:/audiobooks
      - ${Master_Path}/Booksonic/podcasts:/podcasts
      - ${Master_Path}/Booksonic/othermedia:/othermedia
    ports:
      - 4040:4040
    restart: always