---
version: '3'
services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser-Drive
    user: 1000:1003
    ports:
      - 8070:80
    volumes:
      - /home/omar:/srv
      - /home/omar/DockerConfs/FileBrowser/config/filebrowser.db:/database.db
    restart: always
    security_opt:
      - no-new-privileges:true
