version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: Gluetun_VPN_PIA
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - ${Master_Path}/gluetun:/gluetun
    ports:
      # Qbittorrent
      - 8180:8180
      # Jacket
      - 9117:9117
      #SonARR
      - 8989:8989/tcp
      #RadARR
      - 7878:7878/tcp 
      # Chouch Potato
      # - 5050:5050
      #ReadARR
      - 8787:8787
      #ProwLARR
      - 9696:9696
      # mylarr
      - 8090:8090
      # Brave
      - 6901:6901
      # Firefox:
      - 3123:3000

    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=${PIA_VPN_USER}
      - OPENVPN_PASSWORD=${PIA_VPN_PASSWORD}
      - SERVER_REGIONS=Iceland



    # sudo docker run -d --rm --cap-add=NET_ADMIN -e VPN_SERVICE_PROVIDER="private internet access" -e OPENVPN_USER=p3998665 -e OPENVPN_PASSWORD=@^G2r^37$6&5 -v ~/Gluten/gluetun:/gluetun -e SERVER_REGIONS=Netherlands image=qmcgaw/gluetun