---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={$TZ}
      # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ${Master_Path}/Jellyfin/config:/config
      - ${Master_Path}/Jellyfin/cache:/cache
      - /mnt/Drive:/media
     # - /mnt/movies:/media/movies
     # - /mnt/TVSeries:/media/series
     # - /mnt/Podcasts:/media/podcasts
    ports:
      - 8896:8096
      # - 8920:8920 #optional
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    restart: unless-stopped