version: "3.8"
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - JELLYFIN_PublishedServerUrl=192.168.0.16  # replace with your NAS IP
    ports:
      - "8096:8096"
      - "8920:8920"
    volumes:
      - /mnt/Colosseo/data:/media
      - /mnt/Colosseo/APPS/jellyfin/config:/config
      - /mnt/Colosseo/APPS/jellyfin/cache:/cache
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
