---
version: "2.1"
services:
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${Master_Path}/Mylar/config:/config
      - /mnt/Drive/comics:/comics
      - /mnt/Drive/downloads:/downloads
    # ports:
    #   - 8090:8090
    network_mode: 'container:Gluetun_VPN_PIA'
