version: "2.1"
services:
  podgrab:
    image: akhilrex/podgrab
    container_name: podgrab
    environment:
      - CHECK_FREQUENCY=240
     # - PASSWORD=password     ## Uncomment to enable basic authentication, username = podgrab
    volumes:
      - /home/omar/DockerConfs/Podgrab/config:/config
      - /home/omar/podcasts:/assets
    ports:
      - 8282:8080
    restart: always