---
version: "2.1"
services:
  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /home/omar/DockerConfs/Pyload/config:/config
      -  /mnt/Downloads:/downloads
    ports:
      - 8182:8000
      - 9666:9666 #optional
    restart: unless-stopped