---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8180
    volumes:
      - /home/omar/DockerConfs/Qbit/config:/config
      - /home/omar/downloads:/downloads
    network_mode: 'container:Gluetun_VPN_PIA'
    # ports:
      # - 8180:8180
      # - 6881:6881
      # - 6881:6881/udp
    restart: always