---
version: "2.1"
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /home/omar/DockerConfs/Readarr/config:/config
      - /home/omar/books:/books #optional
      - /home/omar/downloads:/downloads #optional
    network_mode: 'container:Gluetun_VPN_PIA'
    # ports:
    #   - 8787:8787
    restart: always