---
version: '3'
services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: 1000:1000
    ports:
      - 8070:80
    volumes:
      - /mnt:/srv
      - ${Master_Path}/MediaFileBrowser/config/filebrowserMnt.db:/database.db
    restart: always
    security_opt:
      - no-new-privileges:true
