version: "3"

services:
  app:
    depends_on:
      - db
    environment:
      PRETTY_URLS: "1"
      HTTPS: "0"
      HTTPS_REDIRECT: "0"
      LANG: "en-US"
      BASE_URL: "http://localhost"
      DB_TYPE: "mysql"
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_USER: "webtrees"
      DB_PASS: "dht8g67G)OF%"
      DB_NAME: "webtrees"
      DB_PREFIX: "wt_"
      WT_USER: "username"
      WT_NAME: "Full Name"
      WT_PASS: "my7G)OF%"
      WT_EMAIL: "me@example.com"
    image: ghcr.io/nathanvaughn/webtrees:2.1.5
    ports:
      - 1180:80
      # - 443:443
    restart: unless-stopped
    volumes:
      # - ~/certs:/certs/
      - app_data:/var/www/webtrees/data/
      - app_media:/var/www/webtrees/media/

  db:
    environment:
      MARIADB_DATABASE: "webtrees"
      MARIADB_USER: "webtrees"
      MARIADB_ROOT_PASSWORD: "dht8g67G)OF%"
      MARIADB_PASSWORD: "dht8g67G)OF%"
    image: docker.io/library/mariadb:latest
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
  app_data:
    driver: local
  app_media:
    driver: local